# fly.toml app configuration file generated for ultimate-api on 2026-09-10T03:58:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ultimate-api'
primary_region = 'yyz'

[build]
  dockerfile = 'Dockerfile'

[env]
  ENVIRONMENT = 'production'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '5m0s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
